site_name: Sam Osian
site_description: Health Data Scientist
site_author: Sam Osian

nav:
  - Home: index.md
  - About: about.md

theme:
  name: material
  language: en
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/book-open-variant
  features:
    - navigation.expand
    - navigation.top
    - navigation.sections
    - navigation.path
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - toc.integrate
    - header.autohide

plugins:
  - search
  - blog:
      blog_dir: .
      archive: false
      categories: false
  - social:
      cards: true
      cards_dir: assets/images/social

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - attr_list
  - footnotes
