site_name: Sam Osian — Health Data Scientist
site_description: Sam Osian — Health Data Scientist
site_author: Sam Osian
site_url: https://sam-osian.com

nav:
  - Home: index.md
  - About: about.md
  - Publications: publications.md
  - PFD Toolkit: https://pfdtoolkit.org/

theme:
  name: material
  language: en
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
  font:
    text: Tinos
    code: Roboto Mono
  icon:
    logo: material/book-open-variant
  favicon: favicon.png
  features:
    - navigation.expand
    - navigation.top
    - navigation.sections
    - navigation.path
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - header.autohide
    - content.tooltips

plugins:
  - search
  - blog:
      blog_dir: .
      archive: false
      categories: false
      post_url_format: "{slug}"
  - social:
      cards: true
      cards_dir: assets/images/social
  - rss:
      match_path: "posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  - glightbox

extra:
  social:
  # github
    - icon: fontawesome/brands/github
      name: sam-osian on GitHub
      link: https://github.com/Sam-Osian
  # linkedin
    - icon: fontawesome/brands/linkedin
      name: sam-osian on LinkedIn
      link: https://www.linkedin.com/in/sam-o-andrews/
  # email
    - icon: /fontawesome/regular/envelope
      name: send me an email
      link: mailto:<samoand@liverpool.ac.uk>

hooks:
  - hooks/socialmedia.py

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - assets/scripts/fade-in.js

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.snippets
  - abbr
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.caption

